name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:

  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  org:
    description: The org to use for the action
    default: ${{ github.event.organization.login }}
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
