name: Slack
on:
  workflow_call:
    inputs:
      org:
        required: true
        description: The organization to check seats.
        type: string
      channel-id:
        required: true
        description: The Slack channel id, channel name, or user id to post message.
        type: string
      seats-remaining:
        required: false
        default: 10
        description: The number of seats that triggers the message
        type: number
    outputs:
      percentage:
        value: ${{jobs.seats.outputs.percentage}}
        description: The percentage of seats used
      remaining:
        value: ${{jobs.seats.outputs.remaining}}
        description: The number of seats remaining
    secrets:
      github-token:
        required: false
        description: GitHub PAT
      slack-bot-token:
        required: false
        description: Slack bot token
jobs:
  seats:
    name: Get Seats Remaining
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: seats
        with:
          org: ${{inputs.org}}
          github-token: ${{secrets.TOKEN}}
      - name: Print
        run: |
          echo "${{steps.seats.outputs.percentage}}% of seats used."
          echo "${{steps.seats.outputs.remaining}} seats remaining"
      - name: Post to a Slack channel
        if: steps.seats.outputs.remaining > inputs.seats-remaining
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{inputs.channel-id}}
          slack-message: "Only ${{steps.seats.outputs.remaining}} GitHub seats remaining!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}