name: Test Slack
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seat-count-slack:
    uses: austenstone/seat-count-action/.github/workflows/slack.yml@main
    with:
      org: octodemo
      github-token: ${{ secrets.TOKEN }}
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      channel-id: 'C040LDABVHQ'
      seats-remaining: 10
    secrets: inherit
