name: Slack Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seat-count-slack:
    name: Seat Count Slack Notification
    uses: ./.github/workflows/slack.yml
    with:
      channel-id: 'C040LDABVHQ'
      SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
    secrets: inherit