# A reusable workflow that sends a slack notification
# when seats reach a given threshold.

name: Seat Count Slack Notification
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  seat-count-slack:
    uses: austenstone/seat-count-action/.github/workflows/slack.yml@main
    with:
      channel-id: 'C040LDABVHQ'
      seats-remaining: 10
    secrets:
      # A GitHub PAT
      # See https://docs.github.com/en/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
      github-token: ${{ secrets.TOKEN }}
      # A slack bot token
      # See https://github.com/marketplace/actions/slack-send#setup-1
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
