name: Run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: seats
        with:
          org: octodemo
          github-token: ${{secrets.TOKEN}}
    outputs:
      percentage: ${{steps.seats.outputs.percentage}}
      remaining: ${{steps.seats.outputs.remaining}}
  less-than-10:
    needs: [seats]
    if: needs.seats.outputs.remaining > 10
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: 'C040LDABVHQ'
        # For posting a simple plain text message
        slack-message: "Less than 10 seats remaining!"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
