name: CI/CD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test-deploy-release:
    name: CI/CD
    uses: ./.github/workflows/slack.yml@main
    with:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      channel-id: 'C040LDABVHQ'
    secrets: inherit