name: Seat Count Slack Notification
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  seat-count-slack:
    uses: austenstone/seat-count-action/.github/workflows/slack.yml@main
    with:
      channel-id: 'C040LDABVHQ'
      seats-remaining: 10
    secrets: inherit
