name: Slack Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seat-count-slack:
    name: Seat Count Slack Notification
    uses: ./.github/workflows/slack.yml
    with:
      channel-id: 'C040LDABVHQ'
      seats-remaining: 10
    secrets: inherit