name: Slack Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seat-count-slack:
    name: CI/CD
    uses: ./.github/workflows/slack.yml
    with:
      SLACK_BOT_TOKEN: secrets.SLACK_BOT_TOKEN
      channel-id: 'C040LDABVHQ'
    secrets: inherit