name: Run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  seats:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          org: octodemo
          github-token: ${{secrets.TOKEN}}
  print:
    runs-on: ubuntu-latest
    needs: [seats]
    steps:
      - run: echo "${{needs.seats.outputs.percentage}}% of seats used."
      - run: echo "${{needs.seats.outputs.remaining}} seats remaining."
